/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import model.Pendaki;

/**
 *
 * @author reyna
 */
public class Beranda extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Beranda.class.getName());
    private model.Pendaki pendakiAktif;
    /**
     * Creates new form Login
     */
    public Beranda() {
        initComponents();
        
    }

   public Beranda(model.Pendaki pendaki) {
    initComponents();
    this.pendakiAktif = pendaki;
    
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnJadwal = new javax.swing.JButton();
        btnJalurPendakian = new javax.swing.JButton();
        btnPemesanan = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnRiwayatPemesanan = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(51, 204, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Selamat Datang, Booking Online Gunung ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, -1, -1));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Contact Person");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 244, -1, -1));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        btnJadwal.setText("Cek Jadwal");
        btnJadwal.addActionListener(this::btnJadwalActionPerformed);
        getContentPane().add(btnJadwal, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, -1, -1));

        btnJalurPendakian.setText("Jalur Pendakian");
        btnJalurPendakian.addActionListener(this::btnJalurPendakianActionPerformed);
        getContentPane().add(btnJalurPendakian, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, -1, -1));

        btnPemesanan.setText("Pemesanan");
        btnPemesanan.addActionListener(this::btnPemesananActionPerformed);
        getContentPane().add(btnPemesanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, -1, -1));

        jButton4.setText("Logout");
        jButton4.addActionListener(this::jButton4ActionPerformed);
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Whatsapp : 0811 4242 89888");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 272, 180, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Instagram : @simaksi.lee");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 294, 160, -1));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btnRiwayatPemesanan.setText("Riwayat Pemesanan");
        btnRiwayatPemesanan.addActionListener(this::btnRiwayatPemesananActionPerformed);
        getContentPane().add(btnRiwayatPemesanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 300, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Logo.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pemandangan (1) (2).png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnJadwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJadwalActionPerformed
        // TODO add your handling code here:
        new CekJadwal().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnJadwalActionPerformed

    private void btnPemesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPemesananActionPerformed
        new Peraturan(this.pendakiAktif).setVisible(true); 
    this.dispose();
    }//GEN-LAST:event_btnPemesananActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int opsi = javax.swing.JOptionPane.showConfirmDialog(this, 
            "Apakah Anda yakin ingin keluar dari aplikasi?", 
            "Konfirmasi Log Out", 
            javax.swing.JOptionPane.YES_NO_OPTION, 
            javax.swing.JOptionPane.QUESTION_MESSAGE);
    
  
    if (opsi == javax.swing.JOptionPane.YES_OPTION) {
        
        this.dispose(); 
        
       
        View.Login loginForm = new View.Login(); 
        loginForm.setVisible(true);
    }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnJalurPendakianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJalurPendakianActionPerformed
        // TODO add your handling code here:
        new GunungDanVia().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnJalurPendakianActionPerformed

    private void btnRiwayatPemesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRiwayatPemesananActionPerformed
        // TODO add your handling code here:
        new Report_Pendaki(this.pendakiAktif.getIdPendaki()).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRiwayatPemesananActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       
    java.awt.EventQueue.invokeLater(() -> {
        new Beranda().setVisible(true);
    });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnJadwal;
    private javax.swing.JButton btnJalurPendakian;
    private javax.swing.JButton btnPemesanan;
    private javax.swing.JButton btnRiwayatPemesanan;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
