/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author reyna
 */
public class CekJadwal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CekJadwal.class.getName());

    /**
     * Creates new form CekJadwal
     */
    public CekJadwal() {
        initComponents();
        controller.BookingController bookingCtrl = new controller.BookingController();
        bookingCtrl.loadGunung((javax.swing.JComboBox) cbGunung);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableJadwal = new javax.swing.JTable();
        btnKembali = new javax.swing.JButton();
        cbGunung = new javax.swing.JComboBox<>();
        txtCari = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(446, 236, 0, 0);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(465, 183, 0, 0);

        jTableJadwal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Jalur", "Tanggal", "Sisa Kuota"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableJadwal);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(90, 90, 470, 280);

        btnKembali.setText("Kembali");
        btnKembali.addActionListener(this::btnKembaliActionPerformed);
        getContentPane().add(btnKembali);
        btnKembali.setBounds(20, 10, 73, 23);

        cbGunung.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbGunung.addActionListener(this::cbGunungActionPerformed);
        getContentPane().add(cbGunung);
        cbGunung.setBounds(230, 20, 180, 22);

        txtCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariKeyReleased(evt);
            }
        });
        getContentPane().add(txtCari);
        txtCari.setBounds(440, 60, 120, 22);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Search");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(400, 60, 37, 16);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pemandangan (1) (2).png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 660, 390);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        // TODO add your handling code here:
        new Beranda().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void cbGunungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbGunungActionPerformed
        // TODO add your handling code here:
        if (cbGunung.getSelectedItem() == null) {
        return;
    }
    
    try {
       
        model.Gunung gunungTerpilih = (model.Gunung) cbGunung.getSelectedItem();
        int idGunung = gunungTerpilih.getIdGunung();
        
        
        controller.BookingController bookingCtrl = new controller.BookingController();
        
       
        bookingCtrl.tampilkanKuotaJadwal(idGunung, jTableJadwal); 
        
    } catch (ClassCastException e) {
        System.out.println("Item di awal bukan objek Gunung: " + e.getMessage());
    } catch (Exception e) {
        e.printStackTrace();
    }
    }//GEN-LAST:event_cbGunungActionPerformed

    private void txtCariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariKeyReleased
        // TODO add your handling code here:
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTableJadwal.getModel();
    
    // 2. Buat objek TableRowSorter untuk menyortir & menyaring model tabel
    javax.swing.table.TableRowSorter<javax.swing.table.DefaultTableModel> sorter = new javax.swing.table.TableRowSorter<>(model);
    jTableJadwal.setRowSorter(sorter);
    
    // 3. Ambil teks yang diketik user di kolom pencarian
    String keyword = txtCari.getText();
    
    // 4. Proses penyaringan data
    if (keyword.trim().length() == 0) {
        sorter.setRowFilter(null); // Jika kolom kosong, tampilkan semua data kembali
    } else {
        // (?i) berguna agar pencarian TIDAK sensitif huruf besar/kecil (case-insensitive)
        sorter.setRowFilter(javax.swing.RowFilter.regexFilter("(?i)" + keyword));
    }
    }//GEN-LAST:event_txtCariKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CekJadwal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKembali;
    private javax.swing.JComboBox<String> cbGunung;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableJadwal;
    private javax.swing.JTextField txtCari;
    // End of variables declaration//GEN-END:variables
}
