/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import controller.AdminController;
import javax.swing.JTable;
import model.Admin;

/**
 *
 * @author reyna
 */
public class DashboardAdmin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DashboardAdmin.class.getName());
        private int idTerpilih = -1;
        private String menuAktif = "";
        
    /**
     * Creates new form DashboardAdmin
     */
    public DashboardAdmin() {
        initComponents();
        jScrollPane1.setVisible(false);
        btnCetak.setVisible(false);
        
    }

    DashboardAdmin(Admin admin) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnVerifikasiPendaftaran = new javax.swing.JButton();
        btnVerifikasiPembayaran = new javax.swing.JButton();
        btnKelolaJalur = new javax.swing.JButton();
        btnCetakLaporan = new javax.swing.JButton();
        btnKritikSaran = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tampilkanDIContent = new javax.swing.JTable();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnCetak = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Dashboard Admin");

        jButton6.setText("Log out");
        jButton6.addActionListener(this::jButton6ActionPerformed);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(133, 133, 133)
                .addComponent(jButton6)
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jButton6))
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 6));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("Halo, Admin");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 12, -1, -1));

        btnVerifikasiPendaftaran.setText("Verifikasi Pendaftaran");
        btnVerifikasiPendaftaran.addActionListener(this::btnVerifikasiPendaftaranActionPerformed);
        jPanel2.add(btnVerifikasiPendaftaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 34, -1, -1));

        btnVerifikasiPembayaran.setText("Verifikasi Pembayaran");
        btnVerifikasiPembayaran.addActionListener(this::btnVerifikasiPembayaranActionPerformed);
        jPanel2.add(btnVerifikasiPembayaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 75, -1, -1));

        btnKelolaJalur.setText("Kelola Jalur Pendakian");
        btnKelolaJalur.addActionListener(this::btnKelolaJalurActionPerformed);
        jPanel2.add(btnKelolaJalur, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 110, -1, -1));

        btnCetakLaporan.setText("Cetak Laporan");
        btnCetakLaporan.addActionListener(this::btnCetakLaporanActionPerformed);
        jPanel2.add(btnCetakLaporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 145, 147, -1));

        btnKritikSaran.setText("Kritik dan Saran");
        btnKritikSaran.addActionListener(this::btnKritikSaranActionPerformed);
        jPanel2.add(btnKritikSaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 180, 147, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 170, 240));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 8));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tampilkanDIContent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tampilkanDIContent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tampilkanDIContentMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tampilkanDIContent);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 8, 424, 220));

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(this::btnUpdateActionPerformed);
        jPanel3.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 240, -1, -1));

        btnDelete.setText("Delete");
        btnDelete.addActionListener(this::btnDeleteActionPerformed);
        jPanel3.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 240, -1, -1));

        btnCetak.setText("CETAK");
        jPanel3.add(btnCetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 440, 280));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pemandangan (1) (2).png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 670, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerifikasiPendaftaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerifikasiPendaftaranActionPerformed
       menuAktif = "VERIFIKASI"; // Set menu aktif
        jScrollPane1.setVisible(true); // Munculkan tabel
        btnUpdate.setVisible(true);
    btnDelete.setVisible(true);
    btnCetak.setVisible(false);
        controller.AdminController adminController = new controller.AdminController();
        adminController.tampilkanPembayaranPending(tampilkanDIContent);
        
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_btnVerifikasiPendaftaranActionPerformed

    private void btnVerifikasiPembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerifikasiPembayaranActionPerformed
        // TODO add your handling code here:
        menuAktif = "verifikasi";
    btnUpdate.setVisible(true);
    btnDelete.setVisible(true);
    btnCetak.setVisible(false);
    // Panggil fungsi untuk mengisi data ke tabel tampilkanDISINI
    loadDataVerifikasiPembayaran();
        
    }//GEN-LAST:event_btnVerifikasiPembayaranActionPerformed

    private void btnKelolaJalurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKelolaJalurActionPerformed
        // TODO add your handling code here:
        menuAktif = "JALUR";
        jScrollPane1.setVisible(true);
        btnUpdate.setVisible(true);
    btnDelete.setVisible(true);
    btnCetak.setVisible(false);
        // Memanggil fungsi load data jalur ke tabel (Sesuaikan dengan method di AdminController-mu)
        // new controller.AdminController().tampilkanSemuaJalur(tampilkanDIContent);
        
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_btnKelolaJalurActionPerformed

    private void btnCetakLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakLaporanActionPerformed
        // TODO add your handling code here:
        menuAktif = "LAPORAN";
        jScrollPane1.setVisible(true);
        btnUpdate.setVisible(false);
        btnDelete.setVisible(false);
        btnCetak.setVisible(true);
        // Memanggil LaporanController sesuai file contoh kodingan manual sebelumnya
        controller.LaporanController laporanCtrl = new controller.LaporanController();
        laporanCtrl.tampilkanLaporan(tampilkanDIContent);
        
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_btnCetakLaporanActionPerformed

    private void btnKritikSaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKritikSaranActionPerformed
        // TODO add your handling code here:
        menuAktif = "KRITIK";
        jScrollPane1.setVisible(true);
        btnUpdate.setVisible(false);
        btnCetakLaporan.setVisible(false);
        btnCetak.setVisible(true);
        controller.LaporanController laporanCtrl = new controller.LaporanController();
        laporanCtrl.tampilkanKritikSaran(tampilkanDIContent);
        
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_btnKritikSaranActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void tampilkanDIContentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tampilkanDIContentMouseClicked
        // TODO add your handling code here:
        int baris = tampilkanDIContent.getSelectedRow();
        if (baris != -1) {
            // Mengambil ID dari kolom pertama (indeks 0)
            idTerpilih = Integer.parseInt(tampilkanDIContent.getValueAt(baris, 0).toString());
        }
    }//GEN-LAST:event_tampilkanDIContentMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        int barisTerpilih = tampilkanDIContent.getSelectedRow();
    
    // Validasi awal: pastikan admin sudah memilih data di tabel
    if (barisTerpilih == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Silakan pilih baris data di tabel terlebih dahulu!");
        return;
    }

   
    
    if ("verifikasi".equals(menuAktif)) {
        // --- 1. LOGIKA UNTUK TABEL VERIFIKASI PEMBAYARAN ---
        String idBooking = tampilkanDIContent.getValueAt(barisTerpilih, 0).toString();
        
        String sql = "UPDATE booking SET status_pembayaran = 'Lunas' WHERE id_booking = ?";
        try (java.sql.Connection conn = config.Koneksi.getInstance().getKoneksi();
             java.sql.PreparedStatement ps = conn.prepareStatement(sql)) {
            
            ps.setString(1, idBooking);
            int hasil = ps.executeUpdate();
            
            if (hasil > 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Pembayaran Berhasil Diverifikasi! Status: Lunas.");
                loadDataVerifikasiPembayaran(); // Refresh tabel pembayaran
            }
        } catch (java.sql.SQLException e) {
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal verifikasi pembayaran: " + e.getMessage());
        }

    } else if ("JALUR".equals(menuAktif)) {
        // --- 2. LOGIKA UNTUK TABEL KELOLA JALUR PENDAKIAN ---
        // Ambil ID Jalur dari kolom ke-0
        String idJalur = tampilkanDIContent.getValueAt(barisTerpilih, 0).toString();
        
        // Contoh: Buka form edit jalur atau ambil data dari textfield admin jika ada
        // String namaJalurBaru = txtNamaJalur.getText(); 
        
        String sql = "UPDATE jalur_pendakian SET nama_jalur = ?, status_jalur = ? WHERE id_jalur = ?";
        try (java.sql.Connection conn = config.Koneksi.getInstance().getKoneksi();
             java.sql.PreparedStatement ps = conn.prepareStatement(sql)) {
            
            // ps.setString(1, namaJalurBaru);
            // ps.setString(2, statusJalurBaru);
            ps.setString(3, idJalur);
            
            int hasil = ps.executeUpdate();
            if (hasil > 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Data Jalur Pendakian berhasil diperbarui!");
                // loadDataJalur(); // Fungsi refresh milik tabel jalurmu
            }
        } catch (java.sql.SQLException e) {
            e.printStackTrace();
        }

    } else if ("VERIFIKASI".equals(menuAktif)) {
        // --- 3. LOGIKA UNTUK TABEL VERIFIKASI PENDAFTARAN (DOKUMEN KTP/KESIHATAN) ---
        String idBooking = tampilkanDIContent.getValueAt(barisTerpilih, 0).toString();
        
        String sql = "UPDATE booking SET status_pendaftaran = 'Disetujui' WHERE id_booking = ?";
        try (java.sql.Connection conn = config.Koneksi.getInstance().getKoneksi();
             java.sql.PreparedStatement ps = conn.prepareStatement(sql)) {
            
            ps.setString(1, idBooking);
            int hasil = ps.executeUpdate();
            
            if (hasil > 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Pendaftaran Berhasil Disetujui!");
                // loadDataPendaftaran(); // Fungsi refresh milik pendaftaran
            }
        } catch (java.sql.SQLException e) {
            e.printStackTrace();
        }
        
    } else {
        // Jika belum ada menu yang dipilih
        javax.swing.JOptionPane.showMessageDialog(this, "Menu tidak dikenali atau belum dipilih.");
    }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        if (idTerpilih == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Silakan pilih data yang ingin dihapus pada tabel!", "Peringatan", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        int konfirmasi = javax.swing.JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin menghapus data dengan ID: " + idTerpilih + "?", "Hapus Data", javax.swing.JOptionPane.YES_NO_OPTION);
        if (konfirmasi == javax.swing.JOptionPane.YES_OPTION) {
            
            if (menuAktif.equals("VERIFIKASI")) {
                // Contoh memanggil controller untuk hapus booking (bisa disesuaikan dengan method AdminController-mu)
                // boolean sukses = new controller.AdminController().hapusBooking(idTerpilih);
                // if (sukses) {
                //     javax.swing.JOptionPane.showMessageDialog(this, "Data pendaftaran berhasil dihapus.");
                //     new controller.AdminController().tampilkanPembayaranPending(tampilkanDIContent);
                // }
            } else if (menuAktif.equals("JALUR")) {
                // Logika hapus jalur
            }
            
            idTerpilih = -1; // Reset ID setelah dihapus
        }
    }//GEN-LAST:event_btnDeleteActionPerformed
private void loadDataVerifikasiPembayaran() {
    controller.AdminController adminCtrl = new controller.AdminController();
    javax.swing.table.DefaultTableModel model = adminCtrl.getPembayaranMenungguVerifikasi();
    
    // MENGGUNAKAN NAMA TABEL ASLIMU
    tampilkanDIContent.setModel(model);
    
    jScrollPane1.setVisible(true);
    tampilkanDIContent.setVisible(true);
    
    this.revalidate();
    this.repaint();
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DashboardAdmin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCetak;
    private javax.swing.JButton btnCetakLaporan;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnKelolaJalur;
    private javax.swing.JButton btnKritikSaran;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnVerifikasiPembayaran;
    private javax.swing.JButton btnVerifikasiPendaftaran;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tampilkanDIContent;
    // End of variables declaration//GEN-END:variables
}
