/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import controller.AdminController;
import javax.swing.JTable;
import model.Admin;

/**
 *
 * @author reyna
 */
public class DashboardAdmin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DashboardAdmin.class.getName());
        private int idTerpilih = -1;
        private String menuAktif = "";
        
    /**
     * Creates new form DashboardAdmin
     */
    public DashboardAdmin() {
        initComponents();
        jScrollPane1.setVisible(false);
        btnCetak.setVisible(false);
        btnLihatBukti.setVisible(false);
        
    }

    DashboardAdmin(Admin admin) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnVerifikasiPendaftaran = new javax.swing.JButton();
        btnVerifikasiPembayaran = new javax.swing.JButton();
        btnKelolaJalur = new javax.swing.JButton();
        btnCetakLaporan = new javax.swing.JButton();
        btnKritikSaran = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tampilkanDIContent = new javax.swing.JTable();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnCetak = new javax.swing.JButton();
        btnLihatBukti = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Dashboard Admin");

        jButton6.setText("Log out");
        jButton6.addActionListener(this::jButton6ActionPerformed);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(133, 133, 133)
                .addComponent(jButton6)
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jButton6))
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 6));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("Halo, Admin");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 12, -1, -1));

        btnVerifikasiPendaftaran.setText("Verifikasi Pendaftaran");
        btnVerifikasiPendaftaran.addActionListener(this::btnVerifikasiPendaftaranActionPerformed);
        jPanel2.add(btnVerifikasiPendaftaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 34, -1, -1));

        btnVerifikasiPembayaran.setText("Verifikasi Pembayaran");
        btnVerifikasiPembayaran.addActionListener(this::btnVerifikasiPembayaranActionPerformed);
        jPanel2.add(btnVerifikasiPembayaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 75, -1, -1));

        btnKelolaJalur.setText("Kelola Jalur Pendakian");
        btnKelolaJalur.addActionListener(this::btnKelolaJalurActionPerformed);
        jPanel2.add(btnKelolaJalur, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 110, -1, -1));

        btnCetakLaporan.setText("Cetak Laporan");
        btnCetakLaporan.addActionListener(this::btnCetakLaporanActionPerformed);
        jPanel2.add(btnCetakLaporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 145, 147, -1));

        btnKritikSaran.setText("Kritik dan Saran");
        btnKritikSaran.addActionListener(this::btnKritikSaranActionPerformed);
        jPanel2.add(btnKritikSaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 180, 147, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 170, 240));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 8));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tampilkanDIContent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tampilkanDIContent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tampilkanDIContentMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tampilkanDIContent);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 8, 424, 220));

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(this::btnUpdateActionPerformed);
        jPanel3.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, -1, -1));

        btnDelete.setText("Delete");
        btnDelete.addActionListener(this::btnDeleteActionPerformed);
        jPanel3.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 240, -1, -1));

        btnCetak.setText("CETAK");
        btnCetak.addActionListener(this::btnCetakActionPerformed);
        jPanel3.add(btnCetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, -1, -1));

        btnLihatBukti.setText("Lihat Bukti");
        btnLihatBukti.addActionListener(this::btnLihatBuktiActionPerformed);
        jPanel3.add(btnLihatBukti, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 440, 280));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pemandangan (1) (2).png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 670, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerifikasiPendaftaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerifikasiPendaftaranActionPerformed
       menuAktif = "PENDAFTARAN"; // Set menu aktif
        jScrollPane1.setVisible(true); // Munculkan tabel
        btnUpdate.setVisible(true);
    btnDelete.setVisible(true);
    btnCetak.setVisible(false);
    btnLihatBukti.setVisible(false);
        loadDataVerifikasiPendaftaran();
    }//GEN-LAST:event_btnVerifikasiPendaftaranActionPerformed

    private void btnVerifikasiPembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerifikasiPembayaranActionPerformed
        // TODO add your handling code here:
        menuAktif = "PEMBAYARAN";
    btnUpdate.setVisible(true);
    btnDelete.setVisible(true);
    btnCetak.setVisible(false);
    btnLihatBukti.setVisible(true);
    // Panggil fungsi untuk mengisi data ke tabel tampilkanDISINI
    loadDataVerifikasiPembayaran();
        
    }//GEN-LAST:event_btnVerifikasiPembayaranActionPerformed

    private void btnKelolaJalurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKelolaJalurActionPerformed
        // TODO add your handling code here:
        menuAktif = "JALUR";
        jScrollPane1.setVisible(true);
        btnUpdate.setVisible(true);
    btnDelete.setVisible(true);
    btnCetak.setVisible(false);
    btnLihatBukti.setVisible(false);
        loadDataJalur();
    }//GEN-LAST:event_btnKelolaJalurActionPerformed

    private void btnCetakLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakLaporanActionPerformed
        // TODO add your handling code here:
        menuAktif = "LAPORAN";
        jScrollPane1.setVisible(true);
        btnUpdate.setVisible(false);
        btnDelete.setVisible(false);
        btnCetak.setVisible(true);
        btnLihatBukti.setVisible(false);
       loadDataLaporan();
    }//GEN-LAST:event_btnCetakLaporanActionPerformed

    private void btnKritikSaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKritikSaranActionPerformed
        // TODO add your handling code here:
        jScrollPane1.setVisible(true);
        btnLihatBukti.setVisible(false);
    
    
    // 2. Tandai menu yang sedang aktif
    menuAktif = "KRITIK";
    jLabel1.setText("MENU: ADUAN / KRITIK & SARAN"); // Mengubah label judul di dashboard
    
    // 3. Sembunyikan tombol yang tidak diperlukan untuk menu ini
    btnCetak.setVisible(false); 
    btnUpdate.setVisible(false);
    btnDelete.setVisible(true);
    
    // 4. Panggil LaporanController untuk load data aduan dari database ke jTable1
    new controller.LaporanController().tampilkanKritikSaran(tampilkanDIContent);
    
    // Re-validate tampilan agar tabel langsung digambar ulang oleh NetBeans
    jPanel2.revalidate();
    jPanel2.repaint();
    }//GEN-LAST:event_btnKritikSaranActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        int opsi = javax.swing.JOptionPane.showConfirmDialog(this, 
            "Apakah Anda yakin ingin keluar dari aplikasi?", 
            "Konfirmasi Log Out", 
            javax.swing.JOptionPane.YES_NO_OPTION, 
            javax.swing.JOptionPane.QUESTION_MESSAGE);
    
    // 2. Jika Pengguna Memilih tombol YES (Iya)
    if (opsi == javax.swing.JOptionPane.YES_OPTION) {
        // Tutup frame Dashboard saat ini
        this.dispose(); 
        
        // Buka kembali halaman Login (Sesuaikan 'Login' dengan nama class JFrame login milikmu)
        View.Login loginForm = new View.Login(); 
        loginForm.setVisible(true);
    }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void tampilkanDIContentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tampilkanDIContentMouseClicked
        // TODO add your handling code here:
        int baris = tampilkanDIContent.getSelectedRow();
    
    if (baris != -1) {
        // 1. KODE ASLI KAMU: Mengambil ID dari kolom pertama (indeks 0)
        idTerpilih = Integer.parseInt(tampilkanDIContent.getValueAt(baris, 0).toString());
        
        // 2. TAMBAHAN UNTUK KELOLA JALUR: Otomatis isi form saat baris diklik
        if ("JALUR".equals(menuAktif)) {
            // Ambil data dari baris tabel yang diklik
            String idJalur = tampilkanDIContent.getValueAt(baris, 0).toString();
            String namaGunung = tampilkanDIContent.getValueAt(baris, 1).toString();
            String namaJalurLama = tampilkanDIContent.getValueAt(baris, 2).toString();
            String statusJalurLama = tampilkanDIContent.getValueAt(baris, 3).toString();
            
            // Panggil fungsi untuk menampilkan form pop-up otomatis
            tampilkanFormPopUpJalur(idJalur, namaGunung, namaJalurLama, statusJalurLama); 
        }
    }
    }//GEN-LAST:event_tampilkanDIContentMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
       int barisTerpilih = tampilkanDIContent.getSelectedRow();
    
    // Validasi awal: pastikan admin sudah memilih data di tabel
    if (barisTerpilih == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Silakan pilih baris data di tabel terlebih dahulu!");
        return;
    }

    // Ambil ID Booking dari kolom pertama (indeks 0)
    String idBooking = tampilkanDIContent.getValueAt(barisTerpilih, 0).toString();

    // =========================================================================
    // A. LOGIKA UNTUK TABEL VERIFIKASI PENDAFTARAN
    // =========================================================================
    if ("PENDAFTARAN".equals(menuAktif)) { 
        // Query mengubah status_booking jadi Disetujui agar ILANG dari pendaftaran
        // dan memastikan status_pembayaran 'Belum Bayar' agar MASUK ke pembayaran
        String sql = "UPDATE booking SET status_booking = 'Disetujui', status_pembayaran = 'Belum Bayar' WHERE id_booking = ?";
        try (java.sql.Connection conn = config.Koneksi.getInstance().getKoneksi();
             java.sql.PreparedStatement ps = conn.prepareStatement(sql)) {
            
            ps.setString(1, idBooking);
            int hasil = ps.executeUpdate();
            
            if (hasil > 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Pendaftaran Disetujui! Data otomatis berpindah ke antrean Verifikasi Pembayaran.");
                loadDataVerifikasiPendaftaran(); // Refresh tabel pendaftaran agar baris langsung hilang dari layar
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Gagal memperbarui data. ID tidak ditemukan.");
            }
        } catch (java.sql.SQLException e) {
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this, "Error database pendaftaran: " + e.getMessage());
        }

    // =========================================================================
    // B. LOGIKA UNTUK TABEL VERIFIKASI PEMBAYARAN
    // =========================================================================
    } else if ("PEMBAYARAN".equals(menuAktif)) { 
        String sql = "UPDATE booking SET status_pembayaran = 'Lunas' WHERE id_booking = ?";
        try (java.sql.Connection conn = config.Koneksi.getInstance().getKoneksi();
             java.sql.PreparedStatement ps = conn.prepareStatement(sql)) {
            
            ps.setString(1, idBooking);
            int hasil = ps.executeUpdate();
            
            if (hasil > 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Pembayaran Berhasil Diverifikasi! Status: Lunas.");
                loadDataVerifikasiPembayaran(); // Refresh tabel pembayaran agar yang lunas langsung hilang
            }
        } catch (java.sql.SQLException e) {
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this, "Error database pembayaran: " + e.getMessage());
        }

    // =========================================================================
    // C. LOGIKA UNTUK TABEL KELOLA JALUR PENDAKIAN
    // =========================================================================
    } else if ("JALUR".equals(menuAktif)) {
        String idJalur = tampilkanDIContent.getValueAt(barisTerpilih, 0).toString();
        String namaJalurLama = tampilkanDIContent.getValueAt(barisTerpilih, 2).toString();
        String statusJalurLama = tampilkanDIContent.getValueAt(barisTerpilih, 3).toString(); // Ambil status lama (Buka/Tutup)
        
        // 1. Tampilkan Pop-up Input untuk mengubah NAMA JALUR
        String namaJalurBaru = javax.swing.JOptionPane.showInputDialog(this, "Ubah Nama Jalur Pendakian:", namaJalurLama);
        
        // Jika admin menekan tombol Cancel pada pop-up nama
        if (namaJalurBaru == null) return; 
        
        namaJalurBaru = namaJalurBaru.trim();
        if (namaJalurBaru.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Nama jalur tidak boleh kosong!");
            return;
        }
        
        // 2. Tampilkan Pop-up Pilihan Pilihan (OptionDialog) untuk STATUS JALUR
        String[] pilihanStatus = {"Buka", "Tutup"};
        int opsiTerpilih = javax.swing.JOptionPane.showOptionDialog(this, 
                "Pilih Status Jalur Terbaru:", 
                "Update Status Jalur", 
                javax.swing.JOptionPane.DEFAULT_OPTION, 
                javax.swing.JOptionPane.QUESTION_MESSAGE, 
                null, pilihanStatus, statusJalurLama);
        
        // Jika admin menutup/silang pop-up opsi tanpa memilih
        if (opsiTerpilih == -1) return; 
        
        // Ambil string berdasarkan tombol yang dipilih ("Buka" atau "Tutup")
        String statusJalurBaru = pilihanStatus[opsiTerpilih];
        
        // 3. Eksekusi ke Database simaksi_online
        String sql = "UPDATE jalur_pendakian SET nama_jalur = ?, status_jalur = ? WHERE id_jalur = ?";
        try (java.sql.Connection conn = config.Koneksi.getInstance().getKoneksi();
             java.sql.PreparedStatement ps = conn.prepareStatement(sql)) {
            
            ps.setString(1, namaJalurBaru);   
            ps.setString(2, statusJalurBaru); 
            ps.setString(3, idJalur);         
            
            int hasil = ps.executeUpdate();
            if (hasil > 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Data Jalur Berhasil Diperbarui!");
                loadDataJalur(); // Refresh tabel biar status terbarunya langsung kelihatan
            }
        } catch (java.sql.SQLException e) {
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this, "Error update jalur: " + e.getMessage());
        }
    
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Menu tidak dikenali. menuAktif saat ini: " + menuAktif);
    }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        if (idTerpilih == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Silakan pilih data yang ingin dihapus pada tabel!", "Peringatan", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        int konfirmasi = javax.swing.JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin menghapus data dengan ID: " + idTerpilih + "?", "Hapus Data", javax.swing.JOptionPane.YES_NO_OPTION);
        if (konfirmasi == javax.swing.JOptionPane.YES_OPTION) {
            
            if (menuAktif.equals("VERIFIKASI")) {
                
            } else if (menuAktif.equals("JALUR")) {
                
            }
            
            idTerpilih = -1; // Reset ID setelah dihapus
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed
        // TODO add your handling code here:
        if (tampilkanDIContent.getRowCount() == 0) {
        javax.swing.JOptionPane.showMessageDialog(this, "Tidak ada data untuk dicetak!");
        return;
    }

    
    javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();
    fileChooser.setDialogTitle("Simpan Laporan PDF");
    
    fileChooser.setSelectedFile(new java.io.File("Laporan_" + menuAktif.toLowerCase() + ".pdf"));

    int userSelection = fileChooser.showSaveDialog(this);

    if (userSelection == javax.swing.JFileChooser.APPROVE_OPTION) {
        java.io.File fileSimpan = fileChooser.getSelectedFile();
        String path = fileSimpan.getAbsolutePath();
        
        
        if (!path.toLowerCase().endsWith(".pdf")) {
            path += ".pdf";
        }

       
        com.itextpdf.text.Document document = new com.itextpdf.text.Document();
        try {
            com.itextpdf.text.pdf.PdfWriter.getInstance(document, new java.io.FileOutputStream(path));
            document.open();

            
            com.itextpdf.text.Font fontJudul = new com.itextpdf.text.Font(com.itextpdf.text.Font.FontFamily.HELVETICA, 16, com.itextpdf.text.Font.BOLD);
            com.itextpdf.text.Paragraph judul = new com.itextpdf.text.Paragraph("DATA " + menuAktif.toUpperCase() + "\n\n", fontJudul);
            judul.setAlignment(com.itextpdf.text.Element.ALIGN_CENTER);
            document.add(judul);

            
            int jumlahKolom = tampilkanDIContent.getColumnCount();
            com.itextpdf.text.pdf.PdfPTable pdfTable = new com.itextpdf.text.pdf.PdfPTable(jumlahKolom);
            pdfTable.setWidthPercentage(100); // Lebar tabel 100% halaman

            
            com.itextpdf.text.Font fontHeader = new com.itextpdf.text.Font(com.itextpdf.text.Font.FontFamily.HELVETICA, 10, com.itextpdf.text.Font.BOLD);
            for (int i = 0; i < jumlahKolom; i++) {
                com.itextpdf.text.pdf.PdfPCell cell = new com.itextpdf.text.pdf.PdfPCell(new com.itextpdf.text.Phrase(tampilkanDIContent.getColumnName(i), fontHeader));
                cell.setHorizontalAlignment(com.itextpdf.text.Element.ALIGN_CENTER);
                cell.setBackgroundColor(com.itextpdf.text.BaseColor.LIGHT_GRAY);
                pdfTable.addCell(cell);
            }

           
            com.itextpdf.text.Font fontIsi = new com.itextpdf.text.Font(com.itextpdf.text.Font.FontFamily.HELVETICA, 9, com.itextpdf.text.Font.NORMAL);
            for (int baris = 0; baris < tampilkanDIContent.getRowCount(); baris++) {
                for (int kolom = 0; kolom < jumlahKolom; kolom++) {
                    Object value = tampilkanDIContent.getValueAt(baris, kolom);
                    String teksCell = (value != null) ? value.toString() : "";
                    pdfTable.addCell(new com.itextpdf.text.Phrase(teksCell, fontIsi));
                }
            }

            document.add(pdfTable);
            javax.swing.JOptionPane.showMessageDialog(this, "Laporan sukses disimpan ke PDF:\n" + path);

        } catch (Exception e) {
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal membuat PDF: " + e.getMessage());
        } finally {
            if (document.isOpen()) {
                document.close(); 
            }
        }
    }
    }//GEN-LAST:event_btnCetakActionPerformed

    private void btnLihatBuktiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLihatBuktiActionPerformed
        // TODO add your handling code here:
       int row = tampilkanDIContent.getSelectedRow();
    if (row == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, 
                "Silakan pilih data transaksi di tabel terlebih dahulu!", 
                "Peringatan", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    // 2. Validasi apakah menu aktif saat ini adalah pembayaran (Anti NullPointerException)
    if (menuAktif == null || !"PEMBAYARAN".equals(menuAktif)) {
        javax.swing.JOptionPane.showMessageDialog(this, 
                "Fitur ini hanya untuk melihat bukti pembayaran pada menu Verifikasi Pembayaran!", 
                "Peringatan", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    // 3. Ambil ID Booking dari kolom pertama (indeks 0) pada baris yang dipilih
    String idBookingTerpilih = tampilkanDIContent.getValueAt(row, 0).toString();
    String pathBukti = null;

    // 4. Query ke database untuk mengambil path gambar bukti_pembayaran
    String sql = "SELECT bukti_pembayaran FROM booking WHERE id_booking = ?";
    
    try (java.sql.Connection conn = config.Koneksi.getInstance().getKoneksi();
         java.sql.PreparedStatement ps = conn.prepareStatement(sql)) {
        
        ps.setString(1, idBookingTerpilih);
        try (java.sql.ResultSet rs = ps.executeQuery()) {
            if (rs.next()) {
                pathBukti = rs.getString("bukti_pembayaran");
            }
        }
        
    } catch (java.sql.SQLException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Gagal mengambil data dari database: " + e.getMessage(), "Database Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

    // 5. Validasi apakah path bukti pembayaran ada/kosong di database
    if (pathBukti == null || pathBukti.trim().isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, 
                "Pendaki belum mengunggah bukti pembayaran untuk kode booking: " + idBookingTerpilih, 
                "Bukti Kosong", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        return;
    }

    // 6. Tampilkan gambar bukti pembayaran ke dalam Pop-up internal Java
    java.io.File fileGambar = new java.io.File(pathBukti);
    if (fileGambar.exists()) {
        // Ambil gambar asli
        javax.swing.ImageIcon originalIcon = new javax.swing.ImageIcon(pathBukti);
        
        // Atur ukuran gambar preview agar pas di layar (lebar 400px, tinggi 500px)
        java.awt.Image img = originalIcon.getImage();
        java.awt.Image scaledImg = img.getScaledInstance(400, 500, java.awt.Image.SCALE_SMOOTH);
        javax.swing.ImageIcon previewIcon = new javax.swing.ImageIcon(scaledImg);
        
        // Munculkan pop-up gambar
        javax.swing.JOptionPane.showMessageDialog(this, 
                "Berikut adalah bukti pembayaran untuk Kode Booking: " + idBookingTerpilih, 
                "Pratinjau Bukti Pembayaran", 
                javax.swing.JOptionPane.INFORMATION_MESSAGE, 
                previewIcon);
    } else {
        // Antisipasi jika path ada di DB tapi file fisiknya terhapus/pindah folder di laptop
        javax.swing.JOptionPane.showMessageDialog(this, 
                "File gambar tidak ditemukan di direktori komputer:\n" + pathBukti, 
                "File Tidak Ditemukan", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnLihatBuktiActionPerformed
// Fungsi untuk memuat data pendaftaran (Hanya status 'Menunggu Verifikasi')
public void loadDataVerifikasiPendaftaran() {
    String[] kolom = {"ID Booking", "Nama Pendaki", "Jalur", "Status Booking"};
    javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(kolom, 0);
    
    String sql = "SELECT b.id_booking, u.nama AS nama_pendaki, j.nama_jalur, b.status_booking " +
                 "FROM booking b " +
                 "JOIN pendaki p ON b.id_pendaki = p.id_pendaki " +
                 "JOIN users u ON p.id_user = u.id_user " +
                 "JOIN jalur_pendakian j ON b.id_jalur = j.id_jalur " +
                 "WHERE b.status_booking = 'Menunggu Verifikasi'"; // Mengunci pendaftaran baru saja

    try (java.sql.Connection conn = config.Koneksi.getInstance().getKoneksi();
         java.sql.Statement stmt = conn.createStatement();
         java.sql.ResultSet rs = stmt.executeQuery(sql)) {

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getString("id_booking"), rs.getString("nama_pendaki"), rs.getString("nama_jalur"), rs.getString("status_booking")
            });
        }
        tampilkanDIContent.setModel(model);
    } catch (java.sql.SQLException e) {
        e.printStackTrace();
    }
}

// Fungsi untuk memuat data pembayaran (Sudah disetujui pendaftarannya, pembayarannya belum lunas)
public void loadDataVerifikasiPembayaran() {
    String[] kolom = {"ID Booking", "Nama Pendaki", "Jalur", "Status Booking", "Status Pembayaran"};
    javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(kolom, 0);
    
    String sql = "SELECT b.id_booking, u.nama AS nama_pendaki, j.nama_jalur, b.status_booking, b.status_pembayaran " +
                 "FROM booking b " +
                 "JOIN pendaki p ON b.id_pendaki = p.id_pendaki " +
                 "JOIN users u ON p.id_user = u.id_user " +
                 "JOIN jalur_pendakian j ON b.id_jalur = j.id_jalur " +
                 "WHERE b.status_booking = 'Disetujui' AND b.status_pembayaran IN ('Belum Bayar', 'Menunggu Verifikasi')";

    try (java.sql.Connection conn = config.Koneksi.getInstance().getKoneksi();
         java.sql.Statement stmt = conn.createStatement();
         java.sql.ResultSet rs = stmt.executeQuery(sql)) {

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getString("id_booking"), rs.getString("nama_pendaki"), rs.getString("nama_jalur"), rs.getString("status_booking"), rs.getString("status_pembayaran")
            });
        }
        tampilkanDIContent.setModel(model);
    } catch (java.sql.SQLException e) {
        e.printStackTrace();
    }
}
public void loadDataLaporan() {
    String[] kolom = {"ID Booking", "Nama Pendaki", "Jalur", "Total Bayar", "Status Pembayaran"};
    javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(kolom, 0);
    
    // KONDISI: Hanya mengambil data yang sudah LUNAS
    String sql = "SELECT b.id_booking, u.nama AS nama_pendaki, j.nama_jalur, b.total_biaya, b.status_pembayaran " +
                 "FROM booking b " +
                 "JOIN pendaki p ON b.id_pendaki = p.id_pendaki " +
                 "JOIN users u ON p.id_user = u.id_user " +
                 "JOIN jalur_pendakian j ON b.id_jalur = j.id_jalur " +
                 "WHERE b.status_pembayaran = 'Lunas'"; // <--- Kunci utama data masuk laporan

    try (java.sql.Connection conn = config.Koneksi.getInstance().getKoneksi();
         java.sql.Statement stmt = conn.createStatement();
         java.sql.ResultSet rs = stmt.executeQuery(sql)) {

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getString("id_booking"),
                rs.getString("nama_pendaki"),
                rs.getString("nama_jalur"),
                rs.getInt("total_biaya"),
                rs.getString("status_pembayaran")
            });
        }
        tampilkanDIContent.setModel(model); // Menampilkan ke tabel utama admin
    } catch (java.sql.SQLException e) {
        e.printStackTrace();
    }
}
public void loadDataJalur() {
    // Menampilkan jScrollPane1 jika sebelumnya disembunyikan
    jScrollPane1.setVisible(true);
    
    String[] kolom = {"ID Jalur", "Nama Gunung", "Nama Jalur", "Status Jalur"};
    javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(kolom, 0);
    
    // Query SQL untuk menggabungkan tabel jalur_pendakian dengan tabel gunung
    String sql = "SELECT j.id_jalur, g.nama_gunung, j.nama_jalur, j.status_jalur " +
                 "FROM jalur_pendakian j " +
                 "JOIN gunung g ON j.id_gunung = g.id_gunung";

    try (java.sql.Connection conn = config.Koneksi.getInstance().getKoneksi();
         java.sql.Statement stmt = conn.createStatement();
         java.sql.ResultSet rs = stmt.executeQuery(sql)) {

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getString("id_jalur"),
                rs.getString("nama_gunung"),
                rs.getString("nama_jalur"),
                rs.getString("status_jalur")
            });
        }
        tampilkanDIContent.setModel(model);
    } catch (java.sql.SQLException e) {
        e.printStackTrace();
        javax.swing.JOptionPane.showMessageDialog(this, "Gagal memuat data jalur: " + e.getMessage());
    }
}
private void tampilkanFormPopUpJalur(String idJalur, String namaGunung, String namaJalurLama, String statusJalurLama) {
    // 1. Membuat frame Pop-up (Dialog) kecil
    javax.swing.JDialog dialog = new javax.swing.JDialog(this, "Kelola Detail Jalur - " + namaGunung, true);
    dialog.setSize(350, 220);
    dialog.setLayout(null);
    dialog.setLocationRelativeTo(this); // Biar pop-up muncul di tengah layar

    // 2. Membuat Label & Text Field untuk Nama Jalur (txt)
    javax.swing.JLabel lblNama = new javax.swing.JLabel("Nama Jalur:");
    lblNama.setBounds(20, 20, 100, 25);
    dialog.add(lblNama);

    javax.swing.JTextField txtNamaJalur = new javax.swing.JTextField(namaJalurLama);
    txtNamaJalur.setBounds(120, 20, 180, 25);
    dialog.add(txtNamaJalur);

    // 3. Membuat Label & Combo Box untuk Status Jalur (cb)
    javax.swing.JLabel lblStatus = new javax.swing.JLabel("Status Jalur:");
    lblStatus.setBounds(20, 60, 100, 25);
    dialog.add(lblStatus);

    String[] pilihanStatus = {"Buka", "Tutup"};
    javax.swing.JComboBox<String> cbStatusJalur = new javax.swing.JComboBox<>(pilihanStatus);
    cbStatusJalur.setSelectedItem(statusJalurLama); // Otomatis pilih sesuai data lama
    cbStatusJalur.setBounds(120, 60, 180, 25);
    dialog.add(cbStatusJalur);

    // 4. Membuat Tombol SIMPAN SIMAKSI
    javax.swing.JButton btnSimpan = new javax.swing.JButton("Simpan Perubahan");
    btnSimpan.setBounds(120, 110, 150, 30);
    dialog.add(btnSimpan);

    // 5. Logika ketika tombol SIMPAN di dalam pop-up diklik
    btnSimpan.addActionListener(new java.awt.event.ActionListener() {
        @Override
        public void actionPerformed(java.awt.event.ActionEvent e) {
            String namaJalurBaru = txtNamaJalur.getText().trim();
            String statusJalurBaru = cbStatusJalur.getSelectedItem().toString();

            if (namaJalurBaru.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(dialog, "Nama jalur tidak boleh kosong!");
                return;
            }

            // Eksekusi Update ke Database simaksi_online
            String sql = "UPDATE jalur_pendakian SET nama_jalur = ?, status_jalur = ? WHERE id_jalur = ?";
            try (java.sql.Connection conn = config.Koneksi.getInstance().getKoneksi();
                 java.sql.PreparedStatement ps = conn.prepareStatement(sql)) {
                
                ps.setString(1, namaJalurBaru);
                ps.setString(2, statusJalurBaru);
                ps.setString(3, idJalur);

                int hasil = ps.executeUpdate();
                if (hasil > 0) {
                    javax.swing.JOptionPane.showMessageDialog(dialog, "Data Jalur Berhasil Diperbarui!");
                    dialog.dispose(); // Tutup jendela pop-up form
                    loadDataJalur();  // Refresh tabel utama admin biar langsung berubah
                }
            } catch (java.sql.SQLException ex) {
                ex.printStackTrace();
                javax.swing.JOptionPane.showMessageDialog(dialog, "Error update database: " + ex.getMessage());
            }
        }
    });

    // Menampilkan jendela pop-up ke layar
    dialog.setVisible(true);
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DashboardAdmin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCetak;
    private javax.swing.JButton btnCetakLaporan;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnKelolaJalur;
    private javax.swing.JButton btnKritikSaran;
    private javax.swing.JButton btnLihatBukti;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnVerifikasiPembayaran;
    private javax.swing.JButton btnVerifikasiPendaftaran;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tampilkanDIContent;
    // End of variables declaration//GEN-END:variables
}
