/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author reyna
 */
public class Pembayaran extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Pembayaran.class.getName());
    private String pathBuktiBaru = null;
    public Pembayaran() {
        initComponents();
    }
    private void updateQRImage() {
        String metode = cbMetodePembayaran.getSelectedItem().toString();
        
        try {
            // Cek pilihan metode pembayaran dan set icon (gambar) yang sesuai
            if (metode.equalsIgnoreCase("GOPAY")) {
                // Mengambil gambar dari package 'images'
                lblQR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Qr.png")));
                lblQR.setText(""); // Kosongkan teks agar tidak menimpa gambar
                
            } else if (metode.equalsIgnoreCase("OVO")) {
                lblQR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Qr.png")));
                lblQR.setText("");
                
            } else {
                // Untuk transfer bank atau metode lainnya
                lblQR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Qr.png")));
                lblQR.setText("");
            }
        } catch (Exception e) {
            // Jika nama file gambar salah atau gambar tidak ditemukan di folder images
            lblQR.setIcon(null); // Hapus gambar sebelumnya (jika ada)
            lblQR.setText("Gambar QR belum tersedia");
            System.out.println("Error load gambar: " + e.getMessage());
        }
    }
    /**
     * Creates new form Pembayaran
     */
    public Pembayaran(String kode, String gunung, int totalBiaya) {
        initComponents(); // Biarkan ini tetap ada (wajib)
        this.setLocationRelativeTo(null); // Agar form muncul di tengah layar
        
        // Memasukkan data parameter ke dalam label-label di desainmu
        lblKodeBooking.setText(kode);
        lblTujuanGunung.setText(gunung);
        lblTotalBiaya.setText("Rp " + String.format("%,d", totalBiaya)); // Format angka jadi ada titiknya
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblQR = new javax.swing.JLabel();
        cbMetodePembayaran = new javax.swing.JComboBox<>();
        lblKodeBooking = new javax.swing.JLabel();
        lblTujuanGunung = new javax.swing.JLabel();
        lblTotalBiaya = new javax.swing.JLabel();
        btnUpload = new javax.swing.JButton();
        lblNamaFile = new javax.swing.JLabel();
        btnKonfirmasi = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 0));
        jPanel1.setForeground(new java.awt.Color(0, 153, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Logo.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Pembayaran");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 50));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 6));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("Kode Booking");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 15, -1, -1));

        jLabel5.setText("Tujuan Gunung");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 46, -1, -1));

        jLabel6.setText("Metode Pembayaran");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 77, -1, -1));

        jLabel7.setText("Total Biaya");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 108, -1, -1));

        lblQR.setText("QR");
        jPanel2.add(lblQR, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 260, 250));

        cbMetodePembayaran.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GOPAY", "DANA", "SHOPEE PAY", "BNI", "BRI", "MANDIRI", "BCA" }));
        cbMetodePembayaran.addActionListener(this::cbMetodePembayaranActionPerformed);
        jPanel2.add(cbMetodePembayaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 74, -1, -1));

        lblKodeBooking.setText("kode");
        jPanel2.add(lblKodeBooking, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 15, -1, -1));

        lblTujuanGunung.setText("tujuan");
        jPanel2.add(lblTujuanGunung, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 46, -1, -1));

        lblTotalBiaya.setText("Total");
        jPanel2.add(lblTotalBiaya, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 108, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 320, 410));

        btnUpload.setText("Upload Bukti");
        btnUpload.addActionListener(this::btnUploadActionPerformed);
        getContentPane().add(btnUpload, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, -1, -1));

        lblNamaFile.setForeground(new java.awt.Color(255, 255, 255));
        lblNamaFile.setText("File");
        getContentPane().add(lblNamaFile, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, -1, -1));

        btnKonfirmasi.setText("Konfirmasi");
        btnKonfirmasi.addActionListener(this::btnKonfirmasiActionPerformed);
        getContentPane().add(btnKonfirmasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, 100, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pemandangan (1) (2).png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 550, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbMetodePembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMetodePembayaranActionPerformed
        // TODO add your handling code here:
        updateQRImage();
    }//GEN-LAST:event_cbMetodePembayaranActionPerformed

    private void btnUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadActionPerformed
        // TODO add your handling code here:
        javax.swing.JFileChooser chooser = new javax.swing.JFileChooser();
    // Filter hanya untuk file gambar
    javax.swing.filechooser.FileNameExtensionFilter filter = new javax.swing.filechooser.FileNameExtensionFilter("Images", "jpg", "png", "jpeg");
    chooser.setFileFilter(filter);
    
    int returnVal = chooser.showOpenDialog(this);
    if(returnVal == javax.swing.JFileChooser.APPROVE_OPTION) {
        java.io.File file = chooser.getSelectedFile();
        pathBuktiBaru = file.getAbsolutePath(); // Ambil lokasi file di komputer
        lblNamaFile.setText(file.getName());    // Tampilkan nama file di label
    }
    }//GEN-LAST:event_btnUploadActionPerformed

    private void btnKonfirmasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKonfirmasiActionPerformed
        // TODO add your handling code here:
        if (pathBuktiBaru == null) {
        javax.swing.JOptionPane.showMessageDialog(this, "Silakan unggah bukti pembayaran terlebih dahulu!", "Peringatan", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    // Ambil ID dari Label
    String kodeBooking = lblKodeBooking.getText();
    System.out.println("Mencoba update ID Booking: " + kodeBooking); // Ini akan muncul di Output NetBeans
    
    // 2. Query UPDATE yang LENGKAP dengan bukti_pembayaran
    String sql = "UPDATE booking SET bukti_pembayaran = ?, status_pembayaran = 'Menunggu Verifikasi' WHERE id_booking = ?";
    
    try (java.sql.Connection conn = config.Koneksi.getInstance().getKoneksi();
         java.sql.PreparedStatement ps = conn.prepareStatement(sql)) {
         
        ps.setString(1, pathBuktiBaru); // Mengisi tanda tanya ke-1 (file gambar)
        ps.setString(2, kodeBooking);   // Mengisi tanda tanya ke-2 (id_booking)
        
        int rows = ps.executeUpdate();
        
        // 3. Pengecekan apakah sukses
        if (rows > 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Bukti berhasil dikirim! Menunggu verifikasi admin.");
            this.dispose(); // Tutup halaman pembayaran
        } else {
            // JIKA MUNCUL PESAN INI, BERARTI ID BOOKING SALAH / TIDAK DITEMUKAN
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal! ID Booking (" + kodeBooking + ") tidak ditemukan di database.\nJangan Run halaman ini secara langsung!");
        }
    } catch (java.sql.SQLException e) {
        e.printStackTrace();
        javax.swing.JOptionPane.showMessageDialog(this, "Gagal mengirim bukti: " + e.getMessage());
    }
    }//GEN-LAST:event_btnKonfirmasiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Pembayaran().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKonfirmasi;
    private javax.swing.JButton btnUpload;
    private javax.swing.JComboBox<String> cbMetodePembayaran;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblKodeBooking;
    private javax.swing.JLabel lblNamaFile;
    private javax.swing.JLabel lblQR;
    private javax.swing.JLabel lblTotalBiaya;
    private javax.swing.JLabel lblTujuanGunung;
    // End of variables declaration//GEN-END:variables
}
