/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import controller.PemesananController;
import javax.swing.JOptionPane;
import model.Booking;
import model.Gunung;
import model.Jalur_Pendakian;
import model.Pendaki;
import model.Promo;

/**
 *
 * @author Dino
 */
public class Pemesanan extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Pemesanan.class.getName());
    private model.Pendaki pendakiAktif;
    /**
     * Creates new form Pemesanan
     */
    public Pemesanan() {
        initComponents();
       controller.BookingController bookingCtrl = new controller.BookingController();
        bookingCtrl.loadGunung((javax.swing.JComboBox) cbGunung);
        generateIdBookingOtomatis();
    }

   public Pemesanan(model.Pendaki pendakiAktif) {
        initComponents();
        this.pendakiAktif = pendakiAktif; //  Data login berhasil diterima di Pemesanan!
        
        controller.BookingController bookingCtrl = new controller.BookingController();
        bookingCtrl.loadGunung((javax.swing.JComboBox) cbGunung);
        generateIdBookingOtomatis();
    }

    private void generateIdBookingOtomatis() {
    String sql = "SELECT MAX(id_booking) AS last_id FROM booking";
    // Menggunakan koneksi database yang sama dengan proyekmu
    java.sql.Connection conn = config.Koneksi.getInstance().getKoneksi();
    
    try (java.sql.PreparedStatement ps = conn.prepareStatement(sql);
         java.sql.ResultSet rs = ps.executeQuery()) {
        
        int nextId = 1; // Default jika tabel booking masih kosong
        
        if (rs.next()) {
            int lastId = rs.getInt("last_id");
            nextId = lastId + 1; // ID berikutnya adalah ID terakhir + 1
        }
        
        // Set angka ID baru tersebut ke JTextField txtIdBooking
        txtIdBooking.setText(String.valueOf(nextId));
        
        // Kunci field-nya agar read-only (pendaki tidak bisa mengubah ID manual)
        txtIdBooking.setEditable(false);
        
    } catch (java.sql.SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Gagal men-generate ID Booking: " + e.getMessage());
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtIdBooking = new javax.swing.JTextField();
        txtKodePromo = new javax.swing.JTextField();
        txtTanggalNaik = new com.toedter.calendar.JDateChooser();
        jTextField4 = new javax.swing.JTextField();
        btnHitung = new javax.swing.JButton();
        btnBayar = new javax.swing.JButton();
        cbGunung = new javax.swing.JComboBox<>();
        cbJalur = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txtTanggalTurun = new com.toedter.calendar.JDateChooser();
        btnLihatPromo = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("BOOKING");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(147, 147, 147))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Form Pemesanan"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("ID Booking");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 38, -1, -1));

        jLabel4.setText("Pilih Gunung");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 69, -1, -1));

        jLabel5.setText("Pilih Jalur");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 109, -1, -1));

        jLabel6.setText("Tanggal Naik");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 149, -1, -1));

        jLabel7.setText("Promo");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 222, -1, -1));

        jLabel8.setText("Total Biaya");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 262, -1, -1));

        txtIdBooking.setEditable(false);
        jPanel2.add(txtIdBooking, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 35, 191, -1));
        jPanel2.add(txtKodePromo, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 219, 191, -1));
        jPanel2.add(txtTanggalNaik, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 149, 191, -1));

        jTextField4.setEditable(false);
        jPanel2.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 259, 191, -1));

        btnHitung.setText("Hitung");
        btnHitung.addActionListener(this::btnHitungActionPerformed);
        jPanel2.add(btnHitung, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, -1, -1));

        btnBayar.setBackground(new java.awt.Color(204, 255, 204));
        btnBayar.setText("Bayar");
        btnBayar.addActionListener(this::btnBayarActionPerformed);
        jPanel2.add(btnBayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, -1, -1));

        cbGunung.addActionListener(this::cbGunungActionPerformed);
        jPanel2.add(cbGunung, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 69, 191, -1));

        cbJalur.addActionListener(this::cbJalurActionPerformed);
        jPanel2.add(cbJalur, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 109, 191, -1));

        jLabel9.setText("Tanggal Turun");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 185, -1, -1));
        jPanel2.add(txtTanggalTurun, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 185, 191, -1));

        btnLihatPromo.setText("Lihat Promo");
        btnLihatPromo.addActionListener(this::btnLihatPromoActionPerformed);
        jPanel2.add(btnLihatPromo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 91, 388, 350));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pemandangan (1) (2).png"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 400, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
        // TODO add your handling code here:
       java.util.Date tglNaik = txtTanggalNaik.getDate();
    java.util.Date tglTurun = txtTanggalTurun.getDate();

    // Validasi input tanggal naik
    if (tglNaik == null) {
        javax.swing.JOptionPane.showMessageDialog(this, "Silakan pilih tanggal naik terlebih dahulu!", "Peringatan", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Validasi input tanggal turun
    if (tglTurun == null) {
        javax.swing.JOptionPane.showMessageDialog(this, "Silakan pilih tanggal turun terlebih dahulu!", "Peringatan", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Validasi agar tanggal turun tidak sebelum tanggal naik
    if (tglTurun.before(tglNaik)) {
        javax.swing.JOptionPane.showMessageDialog(this, "Tanggal turun tidak boleh sebelum tanggal naik!", "Peringatan", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    // 2. Hitung selisih hari sebagai durasi berdasarkan tanggal yang dipilih user
    long diffInMillies = Math.abs(tglTurun.getTime() - tglNaik.getTime());
    long durasiHari = java.util.concurrent.TimeUnit.DAYS.convert(diffInMillies, java.util.concurrent.TimeUnit.MILLISECONDS);

    // Antisipasi jika user memilih tanggal naik dan turun di hari yang sama, durasi dihitung minimal 1 hari
    if (durasiHari == 0) {
        durasiHari = 1;
    }

    // 3. Hitung Biaya Dasar (Sekarang Rp 60.000 per hari sesuai permintaan)
    double tarifPerHari = 60000;
    double biayaDasar = durasiHari * tarifPerHari; 
    double diskon = 0;

    // 4. Cek Kode Promo dari Database
    String inputPromo = txtKodePromo.getText().trim();
    if (!inputPromo.isEmpty()) {
        controller.BookingController bookingCtrl = new controller.BookingController();
        model.Promo promoTerdaftar = bookingCtrl.cekPromoDatabase(inputPromo);

        if (promoTerdaftar != null) {
            // Ambil nilai diskon persenan dari database
            double nilaiDiskon = promoTerdaftar.getDiskon(); 
            if (nilaiDiskon > 1) {
                diskon = biayaDasar * (nilaiDiskon / 100.0); // Jika di DB berbentuk persenan biasa (ex: 10 untuk 10%)
            } else {
                diskon = biayaDasar * nilaiDiskon; // Jika di DB berbentuk desimal langsung (ex: 0.10)
            }
            javax.swing.JOptionPane.showMessageDialog(this, "Kode promo '" + inputPromo + "' berhasil digunakan! Diskon: " + (int)nilaiDiskon + "%", "Sukses", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Kode promo tidak ditemukan di database atau tidak valid.", "Peringatan", javax.swing.JOptionPane.WARNING_MESSAGE);
        }
    }

    // 5. Hitung Total Akhir dan Tampilkan ke jTextField4
    double totalBiaya = biayaDasar - diskon;
    jTextField4.setText(String.valueOf((int) totalBiaya));
    jTextField4.setEditable(false);
    }//GEN-LAST:event_btnHitungActionPerformed

    private void cbGunungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbGunungActionPerformed
        // TODO add your handling code here:
        if (cbGunung.getSelectedItem() == null) {
        return;
    }
    
    try {
        // 2. Ambil object Gunung yang sedang dipilih (casting dari model)
        model.Gunung gunungTerpilih = (model.Gunung) cbGunung.getSelectedItem();
        
        // 3. Ambil id_gunung dari object tersebut
        int idGunung = gunungTerpilih.getIdGunung(); // Pastikan di model Gunung ada method getIdGunung()
        
        // 4. Panggil BookingController untuk me-load data jalur yang sesuai dari database
        controller.BookingController bookingCtrl = new controller.BookingController();
        
        // Netbeans otomatis me-render tipe JComboBox, jika cbJalur kamu bertipe JComboBox<String>, 
        // kamu bisa meng-casting-nya secara mentah atau sesuaikan tipenya ke JComboBox<model.Jalur_Pendakian>
        bookingCtrl.loadJalurByGunung(idGunung, (javax.swing.JComboBox) cbJalur);
        
    } catch (Exception e) {
        e.printStackTrace();
    }
    }//GEN-LAST:event_cbGunungActionPerformed

    private void btnBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBayarActionPerformed
        // TODO add your handling code here:
      try {
        // 1. GANTI PROSES CHECK SESSION: Gunakan objek pendakiAktif yang dikirim dari Beranda
        if (this.pendakiAktif == null) {
            JOptionPane.showMessageDialog(this, "Sesi login habis, silakan login kembali!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            new View.Login().setVisible(true);
            this.dispose();
            return;
        }

        // Ambil ID langsung dari objek pendakiAktif yang valid
        // Catatan: Jika error "cannot find symbol", ganti getIdUser() menjadi getId_user() sesuai method di modelmu
        int idPendaki = this.pendakiAktif.getIdPendaki(); 
        System.out.println("LOG DEBUG -> ID Pendaki yang dikirim ke database: " + idPendaki);
        // 2. Validasi Input Form
        if (txtTanggalNaik.getDate() == null || txtTanggalTurun.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Tanggal Naik dan Tanggal Turun wajib diisi!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (jTextField4.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Hitung total biaya terlebih dahulu!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int idGunung = cbGunung.getSelectedIndex() + 1; 
        int idJalur = cbJalur.getSelectedIndex() + 1;   
        int totalBiaya = Integer.parseInt(jTextField4.getText().trim());

        // Konversi format tanggal JDateChooser (Date) menjadi String (yyyy-MM-dd)
        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd");
        String tglNaik = sdf.format(txtTanggalNaik.getDate());
        String tglTurun = sdf.format(txtTanggalTurun.getDate());

        // 3. Set data ke Model Booking
        model.Booking booking = new model.Booking();
        
        booking.setId_pendaki(idPendaki);
        booking.setId_gunung(idGunung);
        booking.setId_jalur(idJalur);
        booking.setTanggal_naik(tglNaik);   
        booking.setTanggal_turun(tglTurun); 
        booking.setTotal_biaya(totalBiaya);
        booking.setStatus_pembayaran("Belum Bayar");

        
        controller.PemesananController pemesananCtrl = new controller.PemesananController();
        String idBookingBaru = pemesananCtrl.tambahBooking(booking);

        if (idBookingBaru != null) {
            JOptionPane.showMessageDialog(this, "Booking Berhasil! Beralih ke halaman pembayaran.", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            String idBooking = txtIdBooking.getText(); // mengambil ID Booking dari komponen teks
            int totalHarga = totalBiaya;
            String namaGunung = cbGunung.getSelectedItem().toString();
            Pembayaran halamanBayar = new Pembayaran(idBooking, totalBiaya, namaGunung);
            halamanBayar.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Gagal menyimpan data booking ke database.", "Error", JOptionPane.ERROR_MESSAGE);
        }

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Format biaya tidak valid!", "Error", JOptionPane.ERROR_MESSAGE);
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnBayarActionPerformed

    private void cbJalurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbJalurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbJalurActionPerformed

    private void btnLihatPromoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLihatPromoActionPerformed
        StringBuilder sb = new StringBuilder();
    sb.append("🎉 DAFTAR PROMO AKTIF 🎉\n\n");
    
    // 1. SESUAIKAN QUERY SQL (Pilih kolom yang memang ada di tabel promo kamu)
    String sql = "SELECT kode_promo, diskon FROM promo"; 
    
    try (java.sql.Connection conn = config.Koneksi.getInstance().getKoneksi();
         java.sql.PreparedStatement ps = conn.prepareStatement(sql);
         java.sql.ResultSet rs = ps.executeQuery()) {
        
        boolean adaPromo = false;
        int nomor = 1;
        
        while (rs.next()) {
            adaPromo = true;
            
            
            String kodePromo = rs.getString("kode_promo"); 
            int diskon = rs.getInt("diskon");            
            
            sb.append(nomor).append(". Kode: ").append(kodePromo).append("\n");
            sb.append("   - Potongan: ").append(diskon).append("%\n\n");
            nomor++;
        }
        
        if (!adaPromo) {
            sb.append("Saat ini sedang tidak ada promo yang aktif.");
        }
        
    } catch (java.sql.SQLException e) {
        javax.swing.JOptionPane.showMessageDialog(this, 
                "Gagal mengambil data database: " + e.getMessage(), 
                "Database Error", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    javax.swing.JOptionPane.showMessageDialog(this, 
            sb.toString(), 
            "Informasi Promo Simaksi", 
            javax.swing.JOptionPane.INFORMATION_MESSAGE);
    
    }//GEN-LAST:event_btnLihatPromoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Pemesanan().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBayar;
    private javax.swing.JButton btnHitung;
    private javax.swing.JButton btnLihatPromo;
    private javax.swing.JComboBox<String> cbGunung;
    private javax.swing.JComboBox<String> cbJalur;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField txtIdBooking;
    private javax.swing.JTextField txtKodePromo;
    private com.toedter.calendar.JDateChooser txtTanggalNaik;
    private com.toedter.calendar.JDateChooser txtTanggalTurun;
    // End of variables declaration//GEN-END:variables
}
