/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import controller.PemesananController;
import javax.swing.JOptionPane;
import model.Booking;
import model.Gunung;
import model.Jalur_Pendakian;
import model.Promo;

/**
 *
 * @author Dino
 */
public class Pemesanan extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Pemesanan.class.getName());

    /**
     * Creates new form Pemesanan
     */
    public Pemesanan() {
        initComponents();
        controller.BookingController bookingCtrl = new controller.BookingController();
        bookingCtrl.loadGunung((javax.swing.JComboBox) cbGunung);
        generateIdBookingOtomatis();
    }

    private void generateIdBookingOtomatis() {
    String sql = "SELECT MAX(id_booking) AS last_id FROM booking";
    // Menggunakan koneksi database yang sama dengan proyekmu
    java.sql.Connection conn = config.Koneksi.getInstance().getKoneksi();
    
    try (java.sql.PreparedStatement ps = conn.prepareStatement(sql);
         java.sql.ResultSet rs = ps.executeQuery()) {
        
        int nextId = 1; // Default jika tabel booking masih kosong
        
        if (rs.next()) {
            int lastId = rs.getInt("last_id");
            nextId = lastId + 1; // ID berikutnya adalah ID terakhir + 1
        }
        
        // Set angka ID baru tersebut ke JTextField txtIdBooking
        txtIdBooking.setText(String.valueOf(nextId));
        
        // Kunci field-nya agar read-only (pendaki tidak bisa mengubah ID manual)
        txtIdBooking.setEditable(false);
        
    } catch (java.sql.SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Gagal men-generate ID Booking: " + e.getMessage());
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtIdBooking = new javax.swing.JTextField();
        txtKodePromo = new javax.swing.JTextField();
        txtTanggalNaik = new com.toedter.calendar.JDateChooser();
        jTextField4 = new javax.swing.JTextField();
        btnHitung = new javax.swing.JButton();
        btnBayar = new javax.swing.JButton();
        cbGunung = new javax.swing.JComboBox<>();
        cbJalur = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txtTanggalTurun = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("BOOKING");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(147, 147, 147))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Form Pemesanan"));

        jLabel3.setText("ID Booking");

        jLabel4.setText("Pilih Gunung");

        jLabel5.setText("Pilih Jalur");

        jLabel6.setText("Tanggal Naik");

        jLabel7.setText("Promo");

        jLabel8.setText("Total Biaya");

        btnHitung.setText("Hitung");
        btnHitung.addActionListener(this::btnHitungActionPerformed);

        btnBayar.setBackground(new java.awt.Color(204, 255, 204));
        btnBayar.setText("Bayar");
        btnBayar.addActionListener(this::btnBayarActionPerformed);

        cbGunung.addActionListener(this::cbGunungActionPerformed);

        jLabel9.setText("Tanggal Turun");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(btnHitung)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBayar))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIdBooking)
                            .addComponent(txtKodePromo)
                            .addComponent(txtTanggalNaik, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField4)
                            .addComponent(cbGunung, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbJalur, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTanggalTurun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(31, 31, 31))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtIdBooking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(cbGunung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(cbJalur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txtTanggalNaik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTanggalTurun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtKodePromo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHitung)
                    .addComponent(btnBayar))
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 91, 388, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pemandangan (1) (2).png"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 400, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
        // TODO add your handling code here:
       // 1. Ambil Tanggal Naik dan Tanggal Turun dari kedua JDateChooser
    java.util.Date tglNaik = txtTanggalNaik.getDate();
        if (tglNaik == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Silakan pilih tanggal naik terlebih dahulu!", "Peringatan", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 2. Hitung Otomatis Tanggal Turun (Misal durasi standar pendakian adalah 2 hari)
        long duaHariMilis = 2L * 24 * 60 * 60 * 1000;
        java.util.Date tglTurun = new java.util.Date(tglNaik.getTime() + duaHariMilis);

        // Hitung selisih hari sebagai durasi
        long diffInMillies = Math.abs(tglTurun.getTime() - tglNaik.getTime());
        long durasiHari = java.util.concurrent.TimeUnit.DAYS.convert(diffInMillies, java.util.concurrent.TimeUnit.MILLISECONDS);

        // 3. Hitung Biaya Dasar (Misal Rp 30.000 per hari)
        double tarifPerHari = 30000;
        double biayaDasar = durasiHari * tarifPerHari; 
        double diskon = 0;

        // 4. LOGIKA BARU: Cek Kode Promo dari Database
        String inputPromo = txtKodePromo.getText().trim();
        if (!inputPromo.isEmpty()) {
            controller.BookingController bookingCtrl = new controller.BookingController();
            model.Promo promoTerdaftar = bookingCtrl.cekPromoDatabase(inputPromo);

            if (promoTerdaftar != null) {
                // Ambil nilai diskon dari DB (Misal jika di DB bernilai 20, maka dibagi 100)
                double nilaiDiskon = promoTerdaftar.getDiskon(); 
                if (nilaiDiskon > 1) {
                    diskon = biayaDasar * (nilaiDiskon / 100.0); // Jika di DB berbentuk persenan biasa (ex: 20)
                } else {
                    diskon = biayaDasar * nilaiDiskon; // Jika di DB berbentuk desimal langsung (ex: 0.20)
                }
                javax.swing.JOptionPane.showMessageDialog(this, "Kode promo '" + inputPromo + "' berhasil digunakan!", "Sukses", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Kode promo tidak ditemukan di database atau tidak valid.", "Peringatan", javax.swing.JOptionPane.WARNING_MESSAGE);
            }
        }

        // 5. Hitung Total Akhir dan Tampilkan ke jTextField4
        double totalBiaya = biayaDasar - diskon;
        jTextField4.setText(String.valueOf((int) totalBiaya));
        jTextField4.setEditable(false);
    }//GEN-LAST:event_btnHitungActionPerformed

    private void cbGunungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbGunungActionPerformed
        // TODO add your handling code here:
        if (cbGunung.getSelectedItem() == null) {
        return;
    }
    
    try {
        // 2. Ambil object Gunung yang sedang dipilih (casting dari model)
        model.Gunung gunungTerpilih = (model.Gunung) cbGunung.getSelectedItem();
        
        // 3. Ambil id_gunung dari object tersebut
        int idGunung = gunungTerpilih.getIdGunung(); // Pastikan di model Gunung ada method getIdGunung()
        
        // 4. Panggil BookingController untuk me-load data jalur yang sesuai dari database
        controller.BookingController bookingCtrl = new controller.BookingController();
        
        // Netbeans otomatis me-render tipe JComboBox, jika cbJalur kamu bertipe JComboBox<String>, 
        // kamu bisa meng-casting-nya secara mentah atau sesuaikan tipenya ke JComboBox<model.Jalur_Pendakian>
        bookingCtrl.loadJalurByGunung(idGunung, (javax.swing.JComboBox) cbJalur);
        
    } catch (Exception e) {
        e.printStackTrace();
    }
    }//GEN-LAST:event_cbGunungActionPerformed

    private void btnBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBayarActionPerformed
        // TODO add your handling code here:
        if (cbGunung.getSelectedItem() == null) {
        JOptionPane.showMessageDialog(this, "Silakan pilih gunung terlebih dahulu!");
        return;
    }

    try {
        // 2. Ambil data dari komponen Form Pemesanan kamu
        String kodeBooking = txtIdBooking.getText(); // Mengambil kode booking otomatis
        String tujuanGunung = cbGunung.getSelectedItem().toString(); // Mengambil nama gunung
        
        // Mengambil total bayar (Sesuaikan jTextField4 jika itu adalah field total harga milikmu)
        // Kita bersihkan dulu karakter "Rp", titik, atau spasi jika ada agar bisa diubah ke angka
        String strTotal = jTextField4.getText().replaceAll("[^0-8]", ""); 
        int totalBayar = strTotal.isEmpty() ? 0 : Integer.parseInt(strTotal);

        // 3. PROSES SIMPAN KE DATABASE (Opsional - jika kamu sudah punya kodenya di Controller)
        // Di sini biasanya kamu memanggil controller untuk insert data booking ke database, contoh:
        // pemesananCtrl.simpanBooking(...);

        // 4. BUKA FORM PEMBAYARAN DAN PASSING PARAMETERNYA
        // Pastikan package 'View' ditulis dengan huruf besar/kecil yang sesuai
        View.Pembayaran formBayar = new View.Pembayaran(kodeBooking, tujuanGunung, totalBayar);
        formBayar.setVisible(true);

        // 5. Tutup Form Pemesanan saat ini agar layar bersih
        this.dispose();

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Format total bayar tidak valid: " + e.getMessage());
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat memproses pembayaran: " + e.getMessage());
    }
    }//GEN-LAST:event_btnBayarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Pemesanan().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBayar;
    private javax.swing.JButton btnHitung;
    private javax.swing.JComboBox<String> cbGunung;
    private javax.swing.JComboBox<String> cbJalur;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField txtIdBooking;
    private javax.swing.JTextField txtKodePromo;
    private com.toedter.calendar.JDateChooser txtTanggalNaik;
    private com.toedter.calendar.JDateChooser txtTanggalTurun;
    // End of variables declaration//GEN-END:variables
}
