/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Rectangle;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.File;
import java.io.FileOutputStream;
import javax.swing.JOptionPane;
import java.awt.Desktop;
import model.Pendaki;

/**
 *
 * @author reyna
 */
public class Report_Pendaki extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Report_Pendaki.class.getName());
    private int id_pendaki_aktif;
    /**
     * Creates new form Report_Pendaki
     */
    public Report_Pendaki(Pendaki pendakiAktif) {
        initComponents();
        
    }
public Report_Pendaki(int id_pendaki) {
    initComponents(); // Ini untuk menggambar tombol dan checkbox
    this.id_pendaki_aktif = id_pendaki;
    
    // AMANKAN DI SINI: Jangan biarkan error database merusak tombol UI
    try {
        loadRiwayatPesanan(); 
    } catch (Exception e) {
        System.out.println("Error load data: " + e.getMessage());
        // Aplikasi tidak akan crash, tombol centang kamu tetap akan berfungsi normal
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btnCetakPDF = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtIsiPesan = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        btnKirim = new javax.swing.JButton();
        cbKategori = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnKembali = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel1.setText("Riwayat Pesanan Tiket Simaksi");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 19, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Booking", "Nama Pendaki", "Gunung dan Jalur", "Tanggal Naik", "Status"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 44, -1, 205));

        jButton2.setText("Cetak Laporan");
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 289, -1, -1));

        jButton3.setText("Refresh");
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 289, -1, -1));

        btnCetakPDF.setText("Cetak PDF");
        btnCetakPDF.addActionListener(this::btnCetakPDFActionPerformed);
        jPanel2.add(btnCetakPDF, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 255, -1, -1));

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(this::btnRefreshActionPerformed);
        jPanel2.add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 255, -1, -1));

        jTabbedPane2.addTab("Riwayat Pesanan", jPanel2);

        txtIsiPesan.setColumns(20);
        txtIsiPesan.setRows(5);
        jScrollPane2.setViewportView(txtIsiPesan);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("ISI PESAN  :");

        btnKirim.setText("Kirim Aduan");
        btnKirim.addActionListener(this::btnKirimActionPerformed);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Kategori    :");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(37, 37, 37)
                                .addComponent(cbKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(btnKirim)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnKirim)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Aduan & Kritik Saran", jPanel3);

        getContentPane().add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, 330));

        jPanel1.setBackground(new java.awt.Color(0, 153, 0));
        jPanel1.setForeground(new java.awt.Color(0, 153, 0));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Riwayat Pesanan & Aduan");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(29, 29, 29)
                .addComponent(jLabel5)
                .addContainerGap(90, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 60));

        btnKembali.setText("Kembali");
        btnKembali.addActionListener(this::btnKembaliActionPerformed);
        getContentPane().add(btnKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, -1, 20));
        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pemandangan (1) (2).png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 560, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        // TODO add your handling code here:
        new Beranda().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        loadRiwayatPesanan();
    
    // (Opsional) Kasih notifikasi kecil biar user tahu tabelnya sudah di-refresh
    javax.swing.JOptionPane.showMessageDialog(this, "Data riwayat berhasil diperbarui!");
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnKirimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKirimActionPerformed
        // TODO add your handling code here:
        String tipe = cbKategori.getSelectedItem().toString(); // Sudah sesuai dengan nama variabel JComboBox kamu
    String isiPesan = txtIsiPesan.getText().trim(); // PENTING: Ganti 'txtIsiPesan' dengan nama variabel JTextArea kamu!

    // 2. Validasi agar input tidak kosong
    if (isiPesan.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Isi aduan/kritik/saran tidak boleh kosong!", "Peringatan", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    // 3. Query SQL untuk memasukkan data ke tabel report
    // (Sesuaikan susunan kolom 'tipe_aduan', 'isi_pesan', atau 'isi_report' dengan database MySQL kamu)
    String sql = "INSERT INTO report (tipe_aduan, isi_pesan, id_pendaki) VALUES (?, ?, ?)";

    try (java.sql.Connection conn = config.Koneksi.getInstance().getKoneksi();
         java.sql.PreparedStatement ps = conn.prepareStatement(sql)) {

        ps.setString(1, tipe);
        ps.setString(2, isiPesan);
        ps.setInt(3, this.id_pendaki_aktif); // Menggunakan ID Pendaki aktif yang sedang login

        int rowsInserted = ps.executeUpdate();
        if (rowsInserted > 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Berhasil! Laporan atau kritik & saran Anda telah dikirim ke Admin.");
            txtIsiPesan.setText(""); // Kosongkan kembali form JTextArea setelah berhasil dikirim
        }

    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Gagal mengirim laporan: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }
    }//GEN-LAST:event_btnKirimActionPerformed

    private void btnCetakPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakPDFActionPerformed
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow(); // Sesuaikan jTable1 dengan nama variabel tabelmu
    
    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Silakan pilih data pesanan di tabel terlebih dahulu!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    // 2. Ambil data dari baris yang dipilih
    String idBooking = jTable1.getValueAt(row, 0).toString();
    String gunung = jTable1.getValueAt(row, 1).toString();
    String jalur = jTable1.getValueAt(row, 2).toString();
    String tglNaik = jTable1.getValueAt(row, 3).toString();
    String totalBiaya = jTable1.getValueAt(row, 4).toString();
    String status = jTable1.getValueAt(row, 5).toString();
    
    // 3. Tentukan nama dan lokasi file PDF
    String namaFile = "Struk_Booking_" + idBooking + ".pdf";
    
    try {
        // 4. Buat ukuran kertas mirip Struk Kasir (Lebar 250, Tinggi 400)
        Rectangle ukuranStruk = new Rectangle(250, 400);
        Document document = new Document(ukuranStruk, 15, 15, 20, 20); // (ukuran, margin kiri, kanan, atas, bawah)
        
        PdfWriter.getInstance(document, new FileOutputStream(namaFile));
        document.open();
        
        // 5. Setup Font untuk Struk
        Font fontHeader = new Font(Font.FontFamily.HELVETICA, 12, Font.BOLD);
        Font fontBody = new Font(Font.FontFamily.COURIER, 9, Font.NORMAL); // Pake font Courier agar rapi seperti mesin kasir
        Font fontBold = new Font(Font.FontFamily.COURIER, 10, Font.BOLD);
        
        // 6. Desain Isi Struk
        // -- HEADER --
        Paragraph namaToko = new Paragraph("SIMAKSI GUNUNG", fontHeader);
        namaToko.setAlignment(Element.ALIGN_CENTER);
        document.add(namaToko);
        
        Paragraph alamat = new Paragraph("Pemesanan Tiket Pendakian\n==============================", fontBody);
        alamat.setAlignment(Element.ALIGN_CENTER);
        document.add(alamat);
        
        // -- BODY (INFO BOOKING) --
        document.add(new Paragraph("ID Booking : " + idBooking, fontBody));
        document.add(new Paragraph("Tgl Naik   : " + tglNaik, fontBody));
        document.add(new Paragraph("------------------------------", fontBody));
        
        document.add(new Paragraph("Gunung     : " + gunung, fontBody));
        document.add(new Paragraph("Jalur      : " + jalur, fontBody));
        document.add(new Paragraph("Status     : " + status, fontBody));
        document.add(new Paragraph("------------------------------", fontBody));
        
        // -- TOTAL BIAYA --
        Paragraph total = new Paragraph("TOTAL      : " + totalBiaya, fontBold);
        total.setAlignment(Element.ALIGN_RIGHT);
        document.add(total);
        
        document.add(new Paragraph("==============================", fontBody));
        
        // -- FOOTER --
        Paragraph footer = new Paragraph("Terima kasih!\nSimpan struk ini sbg bukti.", fontBody);
        footer.setAlignment(Element.ALIGN_CENTER);
        document.add(footer);
        
        // 7. Tutup dokumen
        document.close();
        
        // 8. Buka otomatis file PDF-nya setelah berhasil dibuat
        JOptionPane.showMessageDialog(this, "Struk PDF berhasil dicetak!");
        File filePdf = new File(namaFile);
        if (filePdf.exists()) {
            Desktop.getDesktop().open(filePdf);
        }
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal mencetak struk: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }
    }//GEN-LAST:event_btnCetakPDFActionPerformed
public void loadRiwayatPesanan() {
    // 1. Cek ID berapa yang sebenarnya sedang dipakai program
    System.out.println("Mencari data untuk ID Pendaki: " + this.id_pendaki_aktif);
    
    String[] kolom = {"ID Booking", "Gunung", "Jalur", "Tanggal Naik", "Total Biaya", "Status"};
    javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(kolom, 0);
    
    String sql = "SELECT b.id_booking, g.nama_gunung, j.nama_jalur, b.tanggal_naik, b.total_biaya, b.status_pembayaran " +
             "FROM booking b " +
             "JOIN gunung g ON b.id_gunung = g.id_gunung " +
             "JOIN jalur_pendakian j ON b.id_jalur = j.id_jalur " +
             "WHERE b.id_pendaki = ? AND b.status_pembayaran = 'Lunas'";

    try (java.sql.Connection conn = config.Koneksi.getInstance().getKoneksi();
         java.sql.PreparedStatement ps = conn.prepareStatement(sql)) {
        
        ps.setInt(1, this.id_pendaki_aktif); 
        java.sql.ResultSet rs = ps.executeQuery();
        
        int jumlahData = 0;
        
        // 2. Mengecek apakah database menemukan datanya
        while (rs.next()) {
            jumlahData++;
            System.out.println("-> Ketemu Data! ID Booking: " + rs.getString("id_booking") + 
                               ", Gunung: " + rs.getString("nama_gunung"));
                               
            model.addRow(new Object[]{
                rs.getString("id_booking"),
                rs.getString("nama_gunung"),
                rs.getString("nama_jalur"),
                rs.getString("tanggal_naik"),
                "Rp " + String.format("%,d", rs.getInt("total_biaya")),
                rs.getString("status_pembayaran")
            });
        }
        
        System.out.println("Total data yang berhasil ditarik: " + jumlahData);
        System.out.println("=================================");
        
        // 3. Masukkan ke tabel
        jTable1.setModel(model); 
        
    } catch (Exception e) {
        System.out.println("!!! ERROR DATABASE !!! : " + e.getMessage());
        e.printStackTrace();
    }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
    new Report_Pendaki(0).setVisible(true); // Memasukkan angka 0 default
});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCetakPDF;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnKirim;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JComboBox<String> cbKategori;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea txtIsiPesan;
    // End of variables declaration//GEN-END:variables
}
